### PR TITLE
Remove gh-pages deployment

### PR DESCRIPTION
**Pull request by JohnTitor**
Seems branch renaming disables gh-pages deployment:
https://github.com/rust-lang/cfg-if/blob/53939dfbfa718333443a4828ba3168f0e18f0dbb/.github/workflows/main.yml#L56

This makes it work again with some tweaks.

## Note

Someone that has admin access to the repo has to enable below on the repo settings:
image

### CODE REVIEW

**Comment by thomcc** [comment]
Do we care about gh-pages deployment given that docs.rs exists now (I suspect that code predates docs.rs)? We could also remove it.

**Comment by JohnTitor** [comment]
If we prefer to remove it instead, I'm happy to! I thought Alex deployed it intentionally and didn't want to break it :)

**Comment by thomcc** [comment]
I think it's just old. Back in the day you had to do this to host your docs since docs.rs didn't exist.

It's not *that* bad if we have a reason for it, but I think I'd rather us remove it if there's no benefit (which seems to be the case).

Maybe we should wait a day or so and see if anybody weighs in about it.

**Comment by thomcc** [comment]
I made a zulip discussion for it: https://rust-lang.zulipchat.com/#narrow/stream/351149-t-libs.2Fcrates/topic/cfg-if.20docs.20publishing

**Review by thomcc — APPROVED** [review]
I think the consensus is that we don't need this, so removal looks great!

**Pull request merged**
